### ISSUE TITLE
wrong assignment to day in task3.algo

### ISSUE THREAD

**Issue by Hamziss** [Hmida-Rojbani/WS-Algo-SS1#2]
1. day := nb % 1000000 will not put the correct value in the variable
ex: 
```
//for nb=181019
day=181019 and not 18
```
**you should change this to:**
`day := Integer(nb / 10000);`

2. Same goes for month
month := nb % 10000; will not put the correct value in the variable
ex:
```
//for nb=181019
month=1019 and not 10
```
**you should change this to:**
`month := Integer(nb % 10000 / 100);`

**Comment by Hmida-Rojbani** [comment]
You are correct I will commit the change
